<?php
// Do not edit this file. Generated by admin script.
// RealEstateManager Configuration file
// General Informations 
$realestatemanager_configuration['release']['version']='1.0 Basic';
$realestatemanager_configuration['release']['date']='17 May 2009';
// edit house 
$realestatemanager_configuration['edithouse']['default']['lang']='';
// price settings
$realestatemanager_configuration['price']['show']='1';
// review settings
$realestatemanager_configuration['reviews']['show']='0';
$realestatemanager_configuration['reviews']['registrationlevel']='-2';
// rent settings
$realestatemanager_configuration['rentstatus']['show']='0';
$realestatemanager_configuration['rentrequest']['registrationlevel']='-2';
// edoc settings
$realestatemanager_configuration['edocs']['allow']='1';
$realestatemanager_configuration['edocs']['show']='1';
$realestatemanager_configuration['edocs']['registrationlevel']='-2';
$realestatemanager_configuration['edocs']['location']='/components/com_realestatemanager/edocs/';
// debuging
$realestatemanager_configuration['debug']='';
$realestatemanager_configuration['page']['items']='10';
// foto size
$realestatemanager_configuration['foto']['high']= '980';
$realestatemanager_configuration['foto']['width']= '380';
// button '[ buy now ]'
$realestatemanager_configuration['buy_now']['show']='0';
$realestatemanager_configuration['buy_now']['allow']['categories']='';
// show in category picture
$realestatemanager_configuration['cat_pic']['show']='1';
// show subcategory
$realestatemanager_configuration['subcategory']['show']='1';
//google Map key
$realestatemanager_configuration['google_map']['key']='ABQIAAAAT8pjOLNVeb07oJMTzqTGJxSX6eBwd2qabuMTvSeqdysOm7gKZRTWROa7VuZtTjhLainKTADwE8vaOw';

?>